<html lang="en">
<head><title>An Introduction to Asynchronous Programming with Twisted</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<link href="../css/springer_epub.css" rel="styleSheet" type="text/css"/>
</head>
<body epub:type="chapter">
 
<!--Begin Abstract--><h1 class="ChapterTitle" lang="en">2.用 Twisted 进行异步编程的介绍</h1>

 
<!--End Abstract--><p class="Para" id="Par2">前一章从基本原则中推导出 Twisted 的事件驱动架构。Twisted 程序和所有事件驱动的程序一样，以增加数据流控制的难度为代价，使并发变得更容易。当事件驱动程序发送的数据超过接收方的处理能力时，它不会通过阻塞 I/O 来自动暂停执行。确定这种情况何时发生以及如何处理是程序的责任。</p>
<p class="Para" id="Par3">通信方之间的数据流动方式也会影响数据在单个程序中的流动方式。因此，<em class="EmphasisTypeItalic ">组成</em>一个事件驱动应用程序的不同组件的策略不同于阻塞程序中使用的策略。</p>
<h2 class="Heading">事件处理程序和合成</h2>
<p>考虑一个不是事件驱动的程序，它使用阻塞 I/O 来执行网络操作:</p>
<pre>def requestField(url, field):
    results = requests.get(url).json()
    return results[field]

</pre>
<p><code>requestField</code>用<code>requests</code> HTTP 库检索一个 URL，将响应的主体解码为 JSON，然后从结果字典中返回所请求的<code>field</code>属性的值。<code>requests</code>使用阻塞 I/O，所以对<code>requestField</code>的调用会暂停整个程序，直到 HTTP 请求所需的网络操作完成。因此，该函数可以假设在它返回之前，<code>results</code>将可用于操作。这个函数的调用者可以做出同样的假设，因为<code>requestField</code>会阻塞它们，直到它计算出结果:</p>
<pre>def someOtherFunction(...):
    ...
    url = calculateURL(...)
    value = requestField(url, 'someInteger')
    return value + 1

x = someOtherFunction(...)

</pre>
<p>在<code>requestField</code>从 JSON 响应中检索到 URL 并提取出<code>someInteger</code>属性的值之前，<code>someOtherFunction</code>和顶级<code>x</code>赋值都无法完成。这是一种<em class="EmphasisTypeItalic ">合成</em> : <code>someOtherFunction</code>调用<code>requestField</code>来完成自己执行的一部分。我们可以通过显式函数组合使这一点更清楚:</p>
<pre>def someOtherFunction(value):
    return value + 1

x = someOtherFunction(requestField(calculateURL(...), 'someInteger'))

</pre>
<p class="Para" id="Par7">这段代码用嵌套的函数调用替换了<code>someOtherFunction</code>的局部变量，但在其他方面是等效的。</p>
<p class="Para" id="Par8">功能组合是组织程序的基本工具。它允许一个程序被<em class="EmphasisTypeItalic ">分解</em>，或者分解成独立的单元，形成一个整体，其行为与未分解的版本完全匹配。这提高了可读性、可重用性和可测试性。</p>
<p>不幸的是，事件处理程序不能像<code>someOtherFunction</code>、<code>requestField</code>和<code>calculateURL</code>那样构成。考虑一个假设的非阻塞版本的<code>requestField</code>:</p>
<pre>def requestField(url, field):
    ??? = nonblockingGet(url)

</pre>
<p class="Para" id="Par10">在非阻塞版本的<code>requestField</code>中，什么可以取代<code>???</code>？这是一个很难回答的问题，因为<code>nonblockingGet</code>不会暂停程序的执行来完成构成对<code>url</code>的 HTTP 请求的网络操作；相反， <code>requestField</code>外的一个事件循环<em class="EmphasisTypeItalic ">复用可读和可写的事件，只要有可能就调用事件处理程序发送和接收数据。没有明显的方法可以从我们假设的<code>nonblockingGet</code>函数中返回<code>event handlers'</code>值。</em></p>
<p>幸运的是，通过将事件处理程序表示为函数，我们可以利用函数组合的通用性将事件驱动的程序分解成独立的组件。让我们假设假设的<code>nonblockingGet</code>函数本身接受一个事件处理函数作为参数，当请求的完成事件发生时，它调用这个函数。这个较高级别的事件将由较低级别的事件合成，类似于我们在第<a href="01.html"> 1 </a>章中看到的传输为了它们的协议而发出一个<code>connectionLost</code>事件的方式。然后我们可以重写<code>requestField</code>来利用这个新论点:</p>
<pre>def requestField(url, field):
    def onCompletion(response):
        document = json.loads(response)
        value = response[field]

    nonblockingGet(url, onCompletion=onCompletion)

</pre>
<p class="Para" id="Par12"><code>onCompletion</code>是一个<em class="EmphasisTypeItalic ">回调</em>，或者是一个可调用的对象，作为一个参数传递给一些其他可调用的对象，这些对象执行一些期望的操作。当该操作完成时，用一些相关的参数调用回调。在这种情况下，<code>nonblockingGet</code>在其 HTTP 请求解析为完整的响应对象时调用其<code>onCompletion</code>回调。在前一章的<code>BuffersWrites</code>实现中，我们看到了一个等价的<code>onCompletion</code>回调；在那里，当所有缓冲的数据都被写入套接字时，它被调用。</p>
<p class="Para" id="Par13">回调在内部组合<em class="EmphasisTypeItalic "/>，而其他函数，比如上面的<code>someOtherFunction</code>示例，在外部组合<em class="EmphasisTypeItalic "/>；在可调用程序的执行过程中，值可用于回调，从而获得所需的结果，而不是从该可调用程序返回。</p>
<p>与<code>nonblockingGet</code>提取事件驱动的 HTTP 请求代码的方式相同，<code>requestField</code>可以通过接受自己的回调提取字段的使用方式。我们将让<code>requestField</code>接受一个<code>useField</code>回调，然后让<code>onCompletion</code>回调调用它:</p>
<pre>def requestField(url, field, useField):
    def onCompletion(response):
        document = json.loads(response)
        value = response[field]
        useField(value)

    nonblockingGet(url, onCompletion=onCompletion)

</pre>
<p>我们可以通过将<code>someOtherFunction</code>作为<code>useField</code>回调来编写一个事件驱动的程序，它相当于我们的阻塞 I/O 版本:</p>
<pre>def someOtherFunction(useValue):
    url = calculateURL(...)
    def addValue(value):
        useValue(value + 1)
    requestField(url,"someInteger", useField=addValue)

</pre>
<p class="Para" id="Par16">反过来，<code>someOtherFunction</code>也必须通过接受其<em class="EmphasisTypeItalic ">自己的</em>回调来进行内部合成，这与之前在外部合成的<code>calculateURL</code>不同。这种回调驱动的方法足以编写任何程序；事实上，在计算机科学的研究中，回调可以被细化为称为<em class="EmphasisTypeItalic ">延续</em>的控制流原语，并被用于一种称为<em class="EmphasisTypeItalic ">延续传递风格</em>的技术中，在这种技术中，函数通过调用它们的延续并产生结果来终止。延续传递风格已经在各种语言编译器中使用，以支持程序分析和优化。</p>
<p class="Para" id="Par17">尽管延续传递式的理论很强大，但读起来和写起来都很笨拙。此外，外部构图——如<code>requestField</code>和<code>calculateURL</code>——和内部构图——如<code>requestField</code>和<code>useField</code>——彼此之间没有明显的构图。例如，很难想象<code>calculateURL</code>如何会被视为回调。最后，错误处理是一个关键的因果关系；想象一下我们将如何以延续传递的方式处理异常！在这个例子中，我们有意省略了任何错误处理，以保持代码足够短，便于阅读。</p>
<p class="Para" id="Par18">幸运的是，<em class="EmphasisTypeItalic ">异步编程</em>提供了一个强大的抽象，简化了事件处理程序的组成，并解决了这些问题。</p>

<h2 class="Heading">什么是异步编程？</h2>
<p class="Para" id="Par19">我们最初的<code>requestField</code>实现是<em class="EmphasisTypeItalic ">同步</em>，因为整个程序的执行是随着时间的推移线性进行的。例如，给定对<code>request.get</code>的两个调用，第一个将在第二个之前完成。同步编程是一种适用于阻塞 I/O 的常见范例。包括 Python 在内的大多数编程语言都默认通过阻塞 I/O 来启用同步操作。</p>
<p class="Para" id="Par20">我们的事件驱动<code>requestField</code>的延续传递风格是一种<em class="EmphasisTypeItalic ">异步编程</em>:当通过<code>nonblockingGet</code>回调的逻辑流暂停直到必要的数据可用时，整个程序的执行继续。两个独立的<code>nonblockingGet</code>调用的执行将交错进行，没有保证它们完成的顺序；一个比另一个早开始并不保证它会先完成。这就是并发的定义。</p>
<p class="Para" id="Par21">利用非阻塞 I/O 的事件驱动程序必然是异步的，因为<em class="EmphasisTypeItalic ">所有的</em> I/O 操作都是基于可以在任何时间以任何顺序到达的事件进行的。值得注意的是，异步程序不需要事件驱动的 I/O；不同的平台基于完全不同的原语提供 I/O 和调度模式。例如，Windows 提供了 I/O 完成端口(IOCP ),它通知程序请求操作的<em class="EmphasisTypeItalic ">完成</em>,而不是执行操作的机会。例如，请求 IOCP 基础设施在套接字上执行读取的程序将被通知读取完成的时间和数据。Twisted 以其 IOCP 反应器的形式对此提供了一些支持，但就我们的目的而言，我们可以将异步编程理解为事件驱动范式的脱节和零碎执行的结果，就像同步编程是阻塞 I/O 的结果一样</p>

<h2 class="Heading">未来值的占位符</h2>
<p class="Para" id="Par22">事件驱动程序中的回调模糊了控制流，因为它们在内部组成了<em class="EmphasisTypeItalic "/>；它们不是将值返回给调用者，而是将结果转发给作为参数接收的回调。这导致了应用程序逻辑和控制流的混合，使重构变得困难，并且在错误发生点和对错误感兴趣的代码之间出现了脱节。</p>
<p>引入一个表示尚未计算的值的对象允许回调在外部<em class="EmphasisTypeItalic ">被组合</em>。考虑一下当允许返回这种占位符时，我们的非阻塞<code>requestField</code>示例是如何变化的:</p>
<pre>def requestField(url, field):
    def onCompletion(response):
        document = json.load(response)

    return jsonDoc[field]
placeholder = nonblockingGet(url)
return placeholder.addCallback(onCompletion)

</pre>
<p class="Para" id="Par24"><code>nonblockingGet</code>现在返回一个<em class="EmphasisTypeItalic ">占位符</em>，这个占位符不是响应，而是一个容器，当响应准备好时，它将被放入这个容器。没有操作的容器不会提供太多好处，所以这个占位符接受它在值准备好时调用的<em class="EmphasisTypeItalic ">回调</em>。我们没有将<code>onCompletion</code>直接传递给<code>nonblockingGet,</code>，而是将其作为回调附加到占位符<code>nonblockingGet</code>的返回中。内部<code>onCompletion</code>回调的实现现在可以返回值——从 JSON 文档中提取的字段——该值将成为后续回调的参数。</p>
<p><code>requestField</code>现在可以暂时删除自己的回调参数，并将占位符返回给<code>someOtherFunction</code>，后者可以添加自己的回调:</p>
<pre>def someOtherFunction(...):
    url = calculateURL(...)
    def addValue(value)
        return value + 1
    placeholder = requestField(url,"someInteger")
    return placeHolder.addCallback(addValue)

</pre>
<p>我们的占位符值并没有完全消除回调。相反，它提供了一个控制流抽象，将回调定位到它们的起始范围，这样它们就可以在外部被组合。当多个回调处理一个异步结果时，这变得更加清晰。考虑以下内部编写的回调:</p>
<pre>def manyCallbacks(url, useValue, ...):
    def addValue(result):
        return divideValue(result + 2)
    def divideValue(result):
        return multiplyValue(result // 3)
    def multiplyValue(result):
        return useValue(result * 4)
    requestField(url, "someInteger", onCompletion=addValue)

</pre>
<p>控制从<code>addValue</code>流向<code>divideValue</code>，最后从<code>multiplyValue</code>退出，进入由<code>manyCallbacks</code>的调用者提供的<code>useValue</code>回调。改变三个内部回调的顺序需要重写每一个。然而，占位符对象将该顺序移出每个回调:</p>
<pre>def manyCallbacks(url, ...):
    def addValue(result):
        return result + 2
    def divideValue(result):
        return result // 3
    def multiplyValue(result):
        return result * 4
placeholder = requestField(url, "someInteger")
placeholder.addCallback(addValue)
placeholder.addCallback(divideValue)
placeholder.addCallback(multiplyValue)
return placeholder

</pre>
<p class="Para" id="Par28"><code>divideValue</code>不再直接依赖于<code>multiplyValue</code>，所以可以在<code>multiplyValue</code>之前移动，甚至不需要改变它或者<code>multiplyValue</code>就可以移除。</p>
<p>回调的实际组合发生在<code>placeholder</code>对象中，其核心实现非常简单。我们将我们的占位符类命名为<code>Deferred</code>,因为它代表一个<em class="EmphasisTypeItalic ">延迟</em>值——一个尚未准备好的值:</p>
<pre>class Deferred(object):
    def __init__ (self):
        self._callbacks = []
    def addCallback(self, callback):
        self._callbacks.append(callback)
    def callback(self, result):
        for callback in self._callbacks:
            result = callback(result)

</pre>
<p class="Para" id="Par30">当结果可用时，<code>Deferred</code>实例的创建者调用<code>callback</code>。每个回调用当前结果调用，其返回值成为传递给下一个回调的结果。这就是上面的<code>onCompletion</code>如何将 HTTP 响应变成唯一感兴趣的 JSON 字段。</p>
<p class="Para" id="Par31">由<code>Deferred</code>的<code>for</code>循环施加的控制流足以依次调用每个回调，但是不能比内部合成的回调更好地处理异常。解决这个问题需要添加某种分支逻辑来检测异常并将异常重新路由到它们的目的地。</p>

<h2 class="Heading">异步异常处理</h2>
<p>同步 Python 代码用<code>try</code>和<code>except</code>处理异常:</p>
<pre>def requestField(url):
    response = requests.get(url).content
    try:
        return response.decode('utf-8')
    except UnicodeDecodeError:
        # Handle this case

</pre>
<p class="Para" id="Par33">通过<code>addCallback</code>方法添加到<code>Deferred</code>的回调在没有异常发生时运行，因此是<code>try</code>块的异步等价物。我们可以通过为<code>except</code>块引入一个类似的回调来添加错误处理，该回调接受异常作为它的参数。像这样被异常调用的回调被称为<em class="EmphasisTypeItalic ">错误返回</em>。</p>
<p class="Para" id="Par34">同步代码可以通过省略<code>try</code>和<code>except</code>来选择让异常向上传播到它的调用者。然而，<code>Deferred</code>的控制流将允许回调引发的异常从<code>for</code>循环向上返回到<code>Deferred.callback</code>的调用者。这将是放置异常处理的错误位置，因为为<code>Deferred</code>提供值的代码不知道添加回调的代码想要的错误处理行为。将这种错误处理封装在我们传递给<code>Deferred</code> s 的<code>errbacks</code>中，允许那些<code>Deferred</code> s 在正确的时间调用它们，而不是麻烦<code>Deferred.callback</code>的调用者。</p>
<p>然后，在回调链的每一步，循环必须捕捉任何异常，并将其转发给下一个 errback。因为每个步骤都可能调用回调或错误返回，所以我们的<code>callbacks</code>列表将更改为包含(<code>callback</code>、<code>errback</code>)对:</p>
<pre>def passthrough(obj):
    return obj

class Deferred(object):
    def __init__ (self):
        self._callbacks = []
    def addCallback(self, callback):
        self._callbacks.append((callback, passthrough))
    def addErrback(self, errback):
        self._callbacks.append((passthrough, errback))
    def callback(self, result):
        for callback, errback in self._callbacks:
            if isinstance(result,BaseException):
                handler = errback
            else:
                handler = callback
            try:
                result = handler(result)
            except BaseExceptionas e:
                result = e

</pre>
<p>循环的每次迭代都检查当前结果。异常被传递给下一个 errback，而其他的都像以前一样被传递给下一个回调。由 errback 或回调引发的任何异常都将成为链中下一个 errback 要处理的结果。这就产生了下面的<code>Deferred</code>代码:</p>
<pre>someDeferred = Deferred()
someDeferred.addCallback(callback)
someDeferred.addErrback(errback)
someDeferred.callback(value)

</pre>
<p>相当于这个同步代码:</p>
<pre>try:
    callback(value)
except BaseExceptionas e:
    errback(e)

</pre>
<p>错误返回通过返回异常来传播异常，并通过返回任何不是<em class="EmphasisTypeItalic ">而不是</em>异常的值来抑制异常。下面的<code>Deferred</code>代码过滤掉 ValueErrors，同时让所有其他异常传播到下一个 errback:</p>
<pre>def suppressValueError(exception):
    if not isinstance(exception, ValueError):
        return exception

someDeferred.addErrback(suppressValueError)

</pre>
<p>当<code>isinstance(exception, ValueError)</code>评估为<code>True</code>时<code>suppressValueError</code>隐式返回<code>None</code>，因此<code>Deferred</code>回调循环中的异常检查将<code>None</code>传递到下一个回调。每隔一个异常从<code>suppressValueError</code>返回，进入<code>for</code>循环，并继续下一个 errback。总的效果相当于下面的同步代码:</p>
<pre>try:
    callback(value)
except ValueError:
    pass

</pre>
<p>当我们考虑它可能遇到异常的两个地方时，<code>Deferred</code>的新控制流的一个方便的结果变得明显:</p>
<ol><li class="ListItem"><p class="Para" id="Par41">在<code>Deferred</code>的回调列表中的任何回调都可能引发异常。例如，我们的<code>manyCallback</code>函数的回调序列中的一个错误可能导致<code>addValue</code>返回<code>None</code>，在这种情况下<code>divideValue</code>将引发一个<code>TypeError</code>。</p>
 </li>
<li class="ListItem"><p class="Para" id="Par42">将实际值传递给<code>Deferred</code>的<code>callback</code>方法的代码可能会引发一个异常。例如，想象一下，<code>nonblockingGet</code>试图将 HTTP 响应的主体解码为 UTF-8，并使用结果回调一个<code>Deferred</code>。如果主体包含非 UTF 8 字节序列，将引发一个<code>UnicodeDecodeError</code>。这种异常意味着实际值永远无法计算，这是<code>Deferred</code>的 errbacks 应该知道的错误情况。</p>
 </li>
</ol>

<p><code>Deferred</code>现在处理这两种情况；第一个问题可以通过在一个<code>try</code>块中运行每个回调和错误返回来解决，而第二个问题可以通过捕捉异常并将其转发给<code>Deferred.callback</code>来解决。考虑一个 HTTP 协议实现，它试图用 UTF-8 解码的响应体调用<code>Deferred</code>的回调:</p>
<pre>class HTTP(protocol.Protocol):
    def dataReceived(self, data):
        self._handleData(data)
        if self.state == "BODY_READY":
            try:
                result = data.decode('utf-8')
            except Exceptionas e:
                result = e
            self.factory.deferred.callback(e)

class HTTPFactory(protocol.Factory)
    protocol = HTTP
    def __init__ (self, deferred):
        self.deferred = deferred

def nonblockingGet(url):
    deferred = Deferred()
    factory = HTTPFactory(deferred)
    ...
    return deferred

</pre>
<p class="Para" id="Par44">这是因为<code>Deferred</code>的<code>for</code>循环通过检查当前结果的性质来开始每次迭代。第一次通过循环，结果是无论调用者提供什么<code>callback</code>；在对<code>Exception</code>进行编码的情况下，上面的代码向<code>callback</code>提供了那个异常。</p>
<p>异常处理现在可以在 errbacks 中本地化，就像应用程序逻辑在回调中本地化一样。这允许我们将同步异常控制流转换为异步异常控制流。此代码:</p>
<pre>def requestField(url, field):
    results = requests.get(url).json()
    return results[field]

def manyOperations(url):
    result = requestField(url, field)
    try:
        result += 2
        result //= 3
        result *= 4
    except TypeError:
        return -1
    return result

</pre>
<p>变成了这样的代码:</p>
<pre>def manyCallbacks(url):
    def addValue(result):
        return result + 2
    def divideValue(result):
        return result // 3
    def multiplyValue(result):
        return result * 4
    def onTypeError(exception):
        if isinstance(exception,TypeError):
            return -1
        else:
            return exception
    deferred = requestField(url, "someInteger")
    deferred.addCallback(addValue)
    deferred.addCallback(divideValue)
    deferred.addCallback(multiplyValue)
    deferred.addErrback(onTypeError)
    return deferred

</pre>
<p class="Para" id="Par47">Twisted 提供了一个<code>Deferred</code>实现，它的 API 是这里显示的 API 的超集；正如我们将在下一节中看到的，真正的<code>Deferred</code>自己组成，并提供额外的功能，如超时和取消。然而，在其核心，它的行为与我们的玩具实现相匹配。</p>

<h2 class="Heading">扭曲的延期介绍</h2>
<p>了解 Twisted 的<code>Deferred</code>的最好方法是在 Python 会话中使用它。我们将从从<code>twisted.internet.defer</code>导入开始:</p>
<pre>&gt;&gt;&gt; from twisted.internet.defer import Deferred

</pre>
<h3 class="Heading">回收</h3>
<p>像我们的玩具实现一样，<code>twisted.internet.defer.Deferred</code>的<code>addCallback</code>方法接受一个回调来添加到实例的回调列表中。与我们的实现不同，Twisted 还接受将传递给回调的位置和关键字参数:</p>
<pre>&gt;&gt;&gt; d = Deferred()
&gt;&gt;&gt; def cbPrint(result, positional, **kwargs):
...     print("result =", result, "positional =", positional,
...           "kwargs =", kwargs)
...
&gt;&gt;&gt; d.addCallback(cbPrint, "positional", keyword=1) is d
True
&gt;&gt;&gt; d.callback("result")
result = result positional = positinal, kwargs = {'keyword': 1}

</pre>
<p class="Para" id="Par50">我们创建一个名为 d 的<code>Deferred</code>，添加<code>cbPrint</code>作为回调，然后用<code>"result". d</code>回调 d，将它传递给<code>cbPrint</code>作为它的第一个位置参数，而传递给<code>d.addCallback</code>的附加参数作为它的剩余参数。</p>
<p>注意，<code>d.addCallback</code>返回 d 本身，这允许像</p>
<pre>d.addCallback(...).addCallback(...).addCallback(...).

</pre>
<p>现在<code>d</code>已经用一个值回调了，它不能再被回调:</p>
<pre>&gt;&gt;&gt; d.callback("whoops")
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "site-packages/twisted/internet/defer.py", line 459, in callback
    self._startRunCallbacks(result)
  File "site-packages/twisted/internet/defer.py", line 560, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError

</pre>
<p>这是因为<code>Deferred</code> s 记得他们被召回的价值:</p>
<pre>&gt;&gt;&gt; d2 = Deferred()
&gt;&gt;&gt; d2.callback("the result")
&lt;Deferred at 0x12345 current result: 'the result'&gt;

</pre>
<p><code>Deferreds</code>存储结果的事实提出了一个问题:当有结果的<code>Deferred</code>被添加了回调时会发生什么？</p>
<pre>&gt;&gt;&gt; d2.addCallback(print)
the result

</pre>
<p>一旦将<code>print</code>作为回调添加到<code>d2</code>中，它就会运行。一个有结果的<code>Deferred</code>s<em class="EmphasisTypeItalic ">立即运行添加给它的回调</em>。人们很容易想象<code>Deferred</code> s 总是代表一个尚不可用的值。然而，假设这一点的代码是错误的，并且是令人沮丧的错误的来源。请考虑以下几点:</p>
<pre>class ReadyOK(twisted.internet.protocol.Protocol):
    def connectionMade(self):
        someDeferred = someAPI()
        def checkAndWriteB(ignored):
            self.transport.write(b"OK\n")
        someDeferred.addCallback(checkAndWriteB)
        self.transport.write(b"READY\n")

</pre>
<p class="Para" id="Par56">顾名思义，这个<code>ReadyOK</code>协议应该用一条<code>READY</code>线路来迎接新的连接，只写<code>OK</code>，当<code>someAPI</code>回叫它的<code>Deferred</code>时就断开。当<code>someDeferred</code>直到<code>connectionMade</code>返回后才被回调时，<code>READY</code>才会出现在<code>OK</code>之前，但这并不能保证；如果<code>someAPI</code>返回<code>someDeferred</code>一个结果，那么<code>OK</code>出现在<code>READY</code>之前。这种预期行顺序的颠倒会破坏正确要求先发送<code>READY</code>的客户端。</p>
<p class="Para" id="Par57">这种情况下的解决方法是将<code>self.transport.write(b"READY\n")</code> <em class="EmphasisTypeItalic ">移到</em> <code>someDeferred = someAPI()</code>之前。您可能需要类似地重新组织您自己的代码，以确保结果的<code>Deferreds</code>不违反不变量。</p>

<h3 class="Heading">错误和失败</h3>
<p><code>Deferreds</code>也有 errbacks 来处理由回调和调用代码提供的异常<code>Deferred.callback</code>。我们首先考虑第一种情况:</p>
<pre>&gt;&gt;&gt; d3 = Deferred()
&gt;&gt;&gt; def cbWillFail(number):
...     1 / number
...
&gt;&gt;&gt; d3.addCallback(cbWillFail)
&lt;Deferred at 0x123456&gt;
&gt;&gt;&gt; d3.addErrback(print)
&lt;Deferred at 0x123456&gt;
&gt;&gt;&gt; d3.callback(0)
[Failure instance: Traceback: &lt;class 'ZeroDivisionError'&gt;: division by zero
&lt;stdin&gt;:1:&lt;module&gt;
site-packages/twisted/internet/defer.py:459:callback
site-packages/twisted/internet/defer.py:567:_startRunCallbacks
--- &lt;exception caught here&gt; ---
site-packages/twisted/internet/defer.py:653:_runCallbacks
&lt;stdin&gt;:2:cbWillFail
]

</pre>
<p class="Para" id="Par59"><code>d3 Deferred</code>有一个将 1 除以其参数的回调函数，内置的<code>print</code>函数作为 errback，因此回调函数引发的任何异常都将出现在我们的交互会话中。用 0 回调<code>d3</code>自然会产生一个<code>ZeroDivisionError</code>，但也会产生其他东西:一个<em class="EmphasisTypeItalic ">失败</em>实例。请注意，<code>Failure</code>字符串表示是用括号([。。。]).errback 打印的是单个故障，而不是有一个故障的<code>list</code>！</p>
<p>Python 2 中的异常对象不包含回溯或其他关于其来源的信息。为了提供尽可能多的上下文，Twisted 引入了<code>Failures</code>作为记录回溯的异步异常的容器类型。在<code>except</code>块中构造的<code>Failure</code>吸收活动异常及其回溯:</p>
<pre>&gt;&gt;&gt; from twisted.python.failure import Failure
&gt;&gt;&gt; try:
...     1 /0
... except:
...     f = Failure()
...
&gt;&gt;&gt; f
&lt;twisted.python.failure.Failure builtins.ZeroDivisionError: division by zero&gt;
&gt;&gt;&gt; f.value ZeroDivisionError('division  by  zero',)
&gt;&gt;&gt; f.getTracebackObject()
&lt;traceback object at 0x1234567&gt;
&gt;&gt;&gt; print(f.getTraceback())Traceback (most recent call last):
--- &lt;exception caught here&gt; ---
  File "&lt;stdin&gt;", line 2, in &lt;module&gt;

builtins.ZeroDivisionError: division by zero

</pre>
<p class="Para" id="Par61"><code>Failure</code>实例在其<code>value</code>属性下存储实际的异常对象，并以几种不同的方式使回溯本身可用。</p>
<p>还有一些方便的方法，可以在出错时轻松地与它们交互。<code>check</code>方法接受多个异常类，并返回属于<code>Failure</code>的异常或<code>None</code>的一个:</p>
<pre>&gt;&gt;&gt; f.check(ValueError)
&gt;&gt;&gt; f.check(ValueError, ZeroDivisionError)
&lt;class 'ZeroDivisionError'&gt;

</pre>
<p><code>Failure.trap</code>的行为类似于<code>check</code>，除了当<code>Failure</code>的异常与任何提供的异常类都不匹配时，它会重新引发异常。这允许 errbacks 复制过滤 except 子句的行为:</p>
<pre>&gt;&gt;&gt; d4 = Deferred()
&gt;&gt;&gt; def cbWillFail(number):
...     1 / 0
...
&gt;&gt;&gt; def ebValueError(failure):
...     failure.trap(ValueError):
...     print("Failure was ValueError")
...
&gt;&gt;&gt; def ebTypeErrorAndZeroDivisionError(failure):
...     exceptionType = failure.trap(TypeError, ZeroDivisionError):
...     print("Failure was", exceptionType)
...
&gt;&gt;&gt; d4.addCallback(cbWillFail)
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; d4.addErrback(ebValueError)
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; d4.addErrback(ebTypeErrorAndZeroDivisionError)
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; d4.callback(0)
Failure was &lt;class 'ZeroDivisionError'&gt;

</pre>
<p><code>ebValueError</code>和<code>ebTypeErrorAndZeroDivisionError</code>的功能类似于同步代码中的两个块:</p>
<pre>try:
    1/0
except ValueError:
    print("Failure was ValueError")
except (TypeError,ZeroDivisionError) as e:    exceptionType = type(e)
    print("Failure was", exceptionType)

</pre>
<p class="Para" id="Par65">最后，<code>Deferreds</code>可以被提供一个<code>Failure</code>或者可以从当前异常合成一个。</p>
<p class="Para" id="Par66">用一个<code>Failure</code>实例回调一个<code>Deferred</code>开始执行它的错误返回。<code>someDeferred.callback(Failure())</code>因此类似于通过我们的玩具实现的<code>callback</code>异常。</p>
<p><code>Deferreds</code>还要暴露一个<code>errback</code>方法。传递这个<code>Failure</code>实例与传递<code>callback</code>实例具有相同的效果；然而，不带参数调用<code>Deferred.errback</code>会导致失败，从而很容易捕获异步处理的异常:</p>
<pre>&gt;&gt;&gt; d5 = Deferred()
&gt;&gt;&gt; d5.addErrback(print)
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; try:
...    1/0
... except:
...    d.errback()
...
[Failure  instance:  Traceback:&lt;  class 'ZeroDivisionError'&gt;:  division  by  zero
---&lt;exception caught here&gt;---
&lt;stdin&gt;:2:&lt;module&gt;
]

</pre>

<h3 class="Heading">撰写延期</h3>
<p class="Para" id="Par68">是一个控制流抽象，支持回调和错误的组合。他们还和自己一起作曲，这样一个<code>Deferred</code>可以侍候一个<code>Deferred</code>。</p>
<p>考虑一个名为<code>outerDeferred</code>的<code>Deferred</code>，它有以下回调序列，其中一个返回<code>innerDeferred</code>，它有自己的<em class="EmphasisTypeItalic ">回调:</em></p>
<pre>&gt;&gt;&gt; outerDeferred = Deferred()
&gt;&gt;&gt; def printAndPassThrough(result, *args):
...     print("printAndPassThrough",
...           " ".join(args), "received", result)
...     return result
...
&gt;&gt;&gt; outerDeferred.addCallback(printAndPassThrough, '1')
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; innerDeferred = Deferred()
&gt;&gt;&gt; innerDeferred.addCallback(printAndPassThrough,  '2',  'a')
&lt;Deferred at 0x123456789&gt;
&gt;&gt;&gt; innerDeferred.addCallback(printAndPassThrough,  '2',  'b')
&lt;Deferred at 0x123456789&gt;
&gt;&gt;&gt; def returnInnerDeferred(result, number):
...     print("returnInnerDeferred #", number, "received", result)
...     print("Returning innerDeferred...")
...     return innerDeferred
...
&gt;&gt;&gt; outerDeferred.addCallback(returnInnerDeferred, '2')
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; outerDeferred.addCallback(printAndPassThrough, '3')
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; outerDeferred.addCallback(printAndPassThrough, '4')
&lt;Deferred at 0x12345678&gt;

</pre>
<p class="Para" id="Par70">回调<code>outerDeferred</code>清楚地调用了标识符为 1 的<code>printAndPassThrough</code>回调，但是当控制到达<code>returnInnerDeferred</code>时会发生什么呢？</p>
<p>我们可以用图<a href="#Fig1"> 2-1 </a>中执行流程的可视化表示来回答这个问题。</p>
<p><img alt="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig1_HTML.jpg" src="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig1_HTML.jpg" style="height:32.82em"/></p>
<p>图 2-1</p><p class="SimplePara"><code>outerDeferred</code>和<code>innerDeferred</code>之间的执行和数据流。执行遵循虚线箭头，而数据流遵循实线箭头。</p>


<p class="Para" id="Par72">标有<strong class="EmphasisTypeBold "> A </strong>的方框代表开始<code>outerDeferred</code>回调循环的<code>outerDeferred.callback(</code> ' <code>result</code> ' <code>)</code>调用，而虚线和实线箭头分别表示执行和数据的流向。</p>
<p>标识符为<code>1</code>的第一个回调函数—<code>printAndPassThrough</code>—接收‘<code>result</code>’作为第一个参数，并打印出一条消息。因为它返回'【T3 '，<code>outerDeferred</code>用相同的对象调用下一个回调。<code>returnInnerDeferred</code>打印它的标识符和一条它正在返回的消息<code>innerDeferred</code>在这样做之前:</p>
<pre>&gt;&gt;&gt; outerDeferred.callback("result")
printAndPassThrough 1 received result
returnInnerDeferred 2 received result
Returning innerDeferred...

</pre>
<p><code>outerDeferred</code>内部的回调循环检测到<code>returnInnerDeferred</code>返回了一个<code>Deferred</code>而不是一个实际值，并且<em class="EmphasisTypeItalic ">暂停</em>自己的回调循环，直到<code>innerDeferred</code>解析为一个值。图<a href="#Fig1"> 2-1 </a>中的虚线箭头表示执行已经转移到<code>innerDeferred</code>处，<code>outerDeferred</code>的<code>repr</code>也是如此:</p>
<pre>&gt;&gt;&gt; outerDeferred
&lt;Deferred at 0x12345678 waiting on Deferred at 0x123456789&gt;

</pre>
<p class="Para" id="Par75">标有<strong class="EmphasisTypeBold "> B </strong>的方框代表继续执行的<code>innerDeferred.callback(</code> ' <code>result</code> ' <code>)</code>调用。自然地，<code>innerDeferred</code>自己的回调，<code>printAndPassThrough</code>的标识符<code>2 a</code>和<code>2 b</code>，现在运行。</p>
<p>一旦<code>innerDeferred</code>已经运行了它所有的回调，执行返回到<code>outerDeferred</code>的回调循环，其中<code>printAndPassThrough</code>的<code>3</code>和<code>4</code>用<code>innerDeferred</code>最后一次回调返回的值执行。</p>
<pre>&gt;&gt;&gt; innerDeferred.callback('inner result')
printAndPassThrough 2 a received inner result
printAndPassThrough 2 b received inner result
printAndPassThrough 3 received inner result
printAndPassThrough 4 received inner result

</pre>
<p class="Para" id="Par77">实际上，<code>printAndPassThrough 3</code>和<code>4</code>变成了<code>innerDeferred</code>的回调。如果任何<code>innerDeferred</code>自己的回调返回<code>Deferred</code> s，它的回调循环将以与<code>outerDeferred</code>相同的方式暂停。</p>
<p>从回调(以及错误返回)返回<code>Deferreds</code>的能力允许在外部组合返回<code>Deferreds</code>的函数:</p>
<pre>def copyURL(sourceURL, targetURL):
    downloadDeferred = retrieveURL(sourceURL)
    def uploadResponse(response):
        return uploadToURL(targetURL, response)
    return downloadDeferred.addCallback(uploadResponse)

</pre>
<p class="Para" id="Par79"><code>copyURL</code>使用两个假设的 API:<code>retrieveURL</code>，它检索一个 URL 的内容；和<code>uploadToURL</code>，它上传数据到一个目标 URL。添加到由<code>retrieveURL</code>返回的<code>Deferred</code>中的<code>uploadResponse</code>回调使用来自源 URL 的数据调用<code>uploadResponse</code>，并返回结果<code>Deferred</code>。记住一个<code>Deferred</code>的<code>addCallback</code>返回相同的实例，所以<code>copyURL</code>返回<code>downloadDeferred</code>给它的调用者。</p>
<p class="Para" id="Par80"><code>copyURL</code>的用户首先等待下载，然后等待上传。<code>copyURL</code>的实现组合返回<code>Deferred</code>的函数，就像它组合回调函数一样，没有任何特殊用途的 API。</p>
<p class="Para" id="Par81">Twisted 的<code>Deferred</code> s 的基本接口允许用户在外部编写回调、错误返回和<code>Deferred</code> s，简化了异步程序的构建。</p>
<p class="Para" id="Par82">异步程序可以从外部组合它们的事件处理程序，这并不是唯一的方法。自从 Twisted 的<code>Deferred</code>问世以来的近 20 年里，Python 已经开发了语言级机制来暂停和恢复特殊类型的函数。</p>


<h2 class="Heading">生成器和内联回调</h2>
<h3 class="Heading">产量</h3>
<p class="Para" id="Par83">Python 从 2.5 版本开始支持<em class="EmphasisTypeItalic ">生成器</em>。生成器是在它们的主体中使用一个<code>yield</code>表达式的函数和方法。调用生成器会返回一个可迭代的<em class="EmphasisTypeItalic ">生成器对象</em>。迭代执行生成器主体，直到下一个<code>yield</code>表达式，此时执行暂停，迭代器计算出<code>yield</code>表达式的操作数。</p>
<p>考虑以下生成器的执行:</p>
<pre>&gt;&gt;&gt; def generatorFunction():
...     print("Begin")
...     yield 1
...     print("Continue")
...     yield 2
...
&gt;&gt;&gt; g = generatorFunction()
&gt;&gt;&gt; g
&lt;generator object generatorFunction at 0x12345690&gt;
&gt;&gt;&gt; result = next(g)
Begin
&gt;&gt;&gt; result
1

</pre>
<p>被调用时返回一个新的生成器对象。请注意，<code>generatorFunction</code>的身体还没有跑起来。内置的<code>next</code>函数推进了一个迭代器；推进生成器对象<code>g</code>开始执行<code>generatorFunction</code>的主体，将<code>Begin</code>输出到我们的交互式 Python 会话中。执行在到达第一个<code>yield</code>表达式时暂停，提供给<code>yield</code>的值成为<code>next</code>调用的返回值。再次调用<code>next</code>继续执行发生器，直到它到达第二个<code>yield</code>:</p>
<pre>&gt;&gt;&gt; nextResult = next(g)
Continue
&gt;&gt;&gt; nextResult
2

</pre>
<p>再次调用<code>next</code>恢复生成器。这一次它的整个身体都被处决了。没有进一步的<code>yields</code>可以暂停，所以生成器对象不能为后续的<code>next</code>调用提供另一个值。根据 Python 的迭代协议，在 generato 对象上调用<code>next</code>会引发<code>StopIteration</code>来表明它已经被耗尽:</p>
<pre>&gt;&gt;&gt; next(g)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p class="Para" id="Par87">因此，生成器遵循与任何其他迭代器相同的 API:要么像上面那样通过对<code>next</code>的显式调用返回值，要么像在<code>for</code>循环中那样通过隐式调用返回值，而<code>StopIteration</code>异常表明不能再返回更多的值。然而，生成器实现的不仅仅是迭代 API。</p>

<h3 class="Heading">派遣</h3>
<p>发生器可以<em class="EmphasisTypeItalic ">接收</em>值，也可以发送它们。<code>yield</code>操作数可以出现在赋值语句的右边。通过将值传递给生成器的<code>send</code>方法，可以使生成器暂停的<code>yield</code>表达式计算出某个值。给定生成器<code>gPrime</code>中的以下<code>yield</code>表达式:</p>
<pre>def gPrime():
    a = yield 4

</pre>
<p><code>gPrime.send(5)</code>导致赋值右侧的<code>yield</code>计算为<code>5</code>，这样生成器中的代码就相当于:</p>
<pre>def gPrime():
    a = 5

</pre>
<p>结果，发电机本地变量<code>a</code>取值为 5。与此同时，<code>gPrime().send(5)</code>调用推进生成器，并评估为<code>4</code>。让我们通过检查一个完全工作的例子及其在图<a href="#Fig2"> 2-2 </a>中的可视化来更详细地探索<code>send</code>的控制流。</p>
<p><img alt="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig2_HTML.jpg" src="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig2_HTML.jpg" style="height:18.22em"/></p>
<p>图 2-2</p><p class="SimplePara">执行和数据流入流出<code>receivingGenerator</code>。执行向下移动，而数据流沿着实线箭头。</p>


<pre>&gt;&gt;&gt; def receivingGenerator():
...     print("Begin")
...     x = 1
...     y = yield x
...     print("Continue")
...     z = yield x + y
...     print(x + y + z)
...
&gt;&gt;&gt; g = receivingGenerator()
&gt;&gt;&gt; result = next(g) # A Begin
&gt;&gt;&gt; result
1
&gt;&gt;&gt; nextResult = g.send(2) # B
Continue
&gt;&gt;&gt; nextResult
3
&gt;&gt;&gt; g.send(3) # C
6
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p class="Para" id="Par91">我们从<code>next</code>开始执行<code>receivingGenerator</code>，与我们开始执行<code>generatorFunction</code>的方式相同；生成器必须总是通过迭代一次来启动。图<a href="#Fig2"> 2-2 </a>中标有<strong class="EmphasisTypeBold "> A </strong>的方框表示对<code>next</code>的初始调用。和以前一样，<code>g</code>一直运行，直到暂停在它的第一个<code>yield</code>表达式上，这个<code>next</code>调用计算那个<code>yield</code>的操作数。因为该操作数是被赋值为 1 的局部变量<code>x</code>，所以<code>next</code>调用的值为 1。从<code>yield x</code>出来的黑色箭头，穿过方框<strong class="EmphasisTypeBold "> A </strong>，在数值<code>1</code>穿过<code>next</code>离开发生器时追踪该数值。</p>
<p class="Para" id="Par92">现在，发电机已经启动，我们可以使用 send 再次恢复它，如框<strong class="EmphasisTypeBold "> B </strong>所示。g. <code>send(2)</code>将值<code>2</code>传递给生成器，生成器将其赋给变量<code>y</code>。执行继续，经过<code>print("Continue")</code>，直到在下一个<code>yield</code>暂停。这里的操作数是表达式<code>x + y</code>，其计算结果为 3，并通过<code>g.send(2)</code>返回。从<code>x + y</code>穿过框<strong class="EmphasisTypeBold "> B </strong>的黑色箭头显示结果 3 采用的退出路径。</p>
<p class="Para" id="Par93">由框<strong class="EmphasisTypeBold "> C </strong>表示的调用<code>g.send(3)</code>，将 3 发送到生成器并再次继续执行，将<code>x</code> + <code>y</code> + <code>z</code> = 6 打印到会话。然而，生成器不能像以前一样暂停执行，因为在<code>receivingGenerator</code>中没有进一步的<code>yield</code>表达式。因为生成器遵循迭代协议，所以当耗尽时它们抛出<code>StopIteration</code>；<code>g.send(3)</code>因此引发 StopIteration，而不是计算一个值，如图<a href="#Fig2"> 2-2 </a>所示，并在示例代码中演示。</p>

<h3 class="Heading">扔</h3>
<p>正如<code>send</code>允许将值传递给生成器一样，<code>throw</code>允许在生成器中引发异常。考虑以下代码:</p>
<pre>&gt;&gt;&gt; def failingGenerator():
...     try:
...         value = yield
...     except ValueError:
...         print("Caught ValueError")
...
&gt;&gt;&gt; tracebackG = failingGenerator()
&gt;&gt;&gt; next(tracebackG)
&gt;&gt;&gt; tracebackG.throw(TypeError())
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 3, in failingGenerator
TypeError
&gt;&gt;&gt; catchingG = failingGenerator()
&gt;&gt;&gt; next(catchingG)
&gt;&gt;&gt; catchingG.throw(ValueError())
Caught ValueError
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p class="Para" id="Par95"><code>failingGenerator</code>将其<code>yield</code>表达式包装在一个<code>try</code>块中，该块的<code>except</code>捕获<code>ValueError</code>，然后打印一条消息。所有其他异常都传递回调用者。</p>
<p class="Para" id="Par96">我们通过调用<code>failingGenerator</code>并将其命名为<code>tracebackG</code>来创建一个新的生成器。我们像往常一样先给<code>next</code>打个电话。注意<code>failingGenerator</code>的<code>yield</code>缺少一个操作数；Python 用<code>None</code>表示值的<em class="EmphasisTypeItalic ">缺失</em>，所以<code>next</code>计算为<code>None</code>(当函数返回<code>None</code>时，迭代 Python 会话不打印<code>None</code>)。在生成器内部，第一个<code>yield</code>本身评估为<code>None</code>，因为<code>next</code>不能向生成器发送任何值。因此，<code>g.send(None)</code>相当于<code>next(g)</code>。当我们研究<em class="EmphasisTypeItalic ">协程</em>时，这种等价将变得非常重要。</p>
<p class="Para" id="Par97">接下来，我们通过<code>throw</code>方法将<code>TypeError</code>扔进<code>tracebackG</code>。发生器恢复到其<code>yield</code>表达式，但是<code>yield</code> <em class="EmphasisTypeItalic ">没有计算出一个值，而是提高了<code>throw</code>传递的<code>TypeError</code></em>。结果回溯在<code>failingGenerator</code>内终止。从回溯中不太清楚的是<code>TypeError</code>从<code>tracebackG.throw</code>上升。这是有意义的:调用<code>throw</code>导致了生成器的恢复，这又引发了<code>TypeError</code>，未处理的异常返回调用堆栈是很自然的。</p>
<p class="Para" id="Par98">一个名为<code>catchingG</code>的新生成器演示了当<code>failingGenerator</code>的<code>except</code>方块遇到<code>ValueError</code>时会发生什么。正如所料，<code>yield</code>引发了传递给<code>throw</code>的异常，正如 Python 的异常处理所料，<code>except</code>块捕获了<code>ValueError</code>并输出了它的消息。然而，没有进一步的<code>yield</code>来暂停发电机，所以这次<code>throw</code>产生一个<code>StopIteration</code>来指示<code>failingGenerator</code>的耗尽。</p>

<h3 class="Heading">带内联回调的异步编程</h3>
<p>生成器暂停和恢复执行对应于<code>Deferred</code>执行回调和错误返回:</p>
<ul class="UnorderedListMarkBullet"><li><p class="Para" id="Par100">当到达一个<code>yield</code>表达式时，生成器暂停其执行，而当一个返回另一个<code>Deferred</code>时，<code>Deferred</code>暂停其回调和出错；</p></li>
<li><p class="Para" id="Par101">暂停的生成器可以通过它的<code>send</code>方法用一个值恢复，而等待另一个<code>Deferred</code>的<code>Deferred</code>在那个<code>Deferred</code>解析为一个值时恢复执行它的回调；</p></li>
<li><p class="Para" id="Par102">暂停的生成器可以通过它的<code>throw</code>方法接收和捕获异常，而等待另一个<code>Deferred</code>的<code>Deferred</code>在那个<code>Deferred</code>解决了异常时继续执行它的 errbacks。</p></li>
</ul>

<p>通过比较以下两个代码示例，我们可以看到这些等效性的作用:</p>
<pre>def requestFieldDeferred(url, field):
    d = nonblockingGet(url)

    def onCompletion(response):
        document = json.load(response)
        return jsonDoc[field]

        def onFailure(failure):
            failure.trap(UnicodeDecodeError)

        d.addCallack(onCompletion)
        d.addErrback(onFailure)

        return d

    def requestFieldGenerator(url, field):
        try:
            document = yield nonblockingGet(url)
        except UnicodeDecodeError:
            pass
        document = json.load(response)
        return jsonDoc[field]

</pre>
<p class="Para" id="Par104"><code>requestFieldDeferred</code>给<code>nonblockingGet</code>的响应<code>Deferred</code>附加一个回调，将响应解码为 JSON 并提取一个属性，以及一个 errback，只隐藏<code>UnicodeDecodeError</code> s</p>
<p class="Para" id="Par105"><code>requestFieldGenerator</code>反而产生<code>nonblockingGet</code>的<code>Deferred</code>。然后，当响应可用时，生成器可以恢复响应，或者如果发生异常，则恢复异常。callback 和 errback 都被移到了调用<code>nonblockingGet</code>的同一个作用域中。将函数体移入调用者被称为<em class="EmphasisTypeItalic ">内联</em>。</p>
<p class="Para" id="Par106">我们不能像写的那样使用<code>requestFieldGenerator</code>: Python 2 不允许生成器返回值，我们需要一个包装器来接受<code>yield</code> ed <code>Deferred</code>,并在<code>Deferred</code>解析为值或异常时安排调用生成器的<code>send</code>或<code>throw</code>。</p>
<p class="Para" id="Par107">Twisted 在<code>twisted.internet.defer.inlineCallbacks</code>中提供了这个包装器。它修饰返回生成器的可调用程序，并在每个产出的<code>Deferred</code>解析为一个值或异常时调用<code>send</code>和<code>throw</code>。反过来，调用修饰的生成器函数或方法的调用者会收到一个<code>Deferred</code>,而不是一个生成器对象。这确保了期望<code>Deferreds</code>的现有 API 与<code>inlineCallbacks</code>无缝协作。</p>
<p>这是我们用<code>inlineCallbacks</code>装饰的<code>requestFieldGenerator</code>:</p>
<pre>from twisted.internet import defer

@defer.inlineCallbacks
def requestFieldGenerator(url, field):
    try:
        document = yield nonblockingGet(url)
    except UnicodeDecodeError:
        pass

    document = json.load(response)
    defer.returnValue(jsonDoc[field])

def someCaller(url, ...):
    requestFieldDeferred = requestFieldGenerator(url,"someProperty")
    ...

</pre>
<p class="Para" id="Par109"><code>returnValue</code>函数抛出一个包含其参数的特殊异常；<code>inlineCallbacks</code>捕捉到这个，并安排用那个值回调<code>requestFieldGenerator</code>。Python 3 中的一个<code>return</code>语句引发了一个等价的异常，<code>inlineCallbacks</code>也会捕获它，所以在只在 Python 3 下运行的代码中<code>returnValue</code>是不必要的。</p>
<p class="Para" id="Par110">通过将代码从回调和错误返回到单个局部范围，生成器使得异步扭曲程序读起来就像同步的一样。短程序尤其受益于随之而来的函数定义的减少和更清晰的控制流。</p>
<p>发电机用熟悉来换取新的困难。最关键的是，生成器函数或方法的调用者不可能知道返回的生成器对象是使用用<code>send</code>发送给它的值，还是默默地忽略它。例如，这两个发生器提供相同的接口:</p>
<pre>def listensToSend():
    a = 1
    b = yield a
    print(a+b)

def ignoresSend():
    a = 1
    yield a
    print(a)

</pre>
<p class="Para" id="Par112">意外地用<code>ignoreSend</code>替换<code>listensToSend</code>会导致一个难以诊断的细微错误。两者都是有效的 Python 代码，适用于不同的环境:<code>listensToSend</code>允许带值的恢复，使其适用于<code>inlineCallbacks</code>，而<code>ignoreSend</code>只是产生一个值，适合于对文件中的行进行操作的处理管道。Python 生成器 API 模糊了这两个不同的用例。</p>
<p class="Para" id="Par113">幸运的是，Python 3 的最新版本提供了为<code>inlineCallbacks</code>风格的生成器量身定制的新语法。</p>


<h2 class="Heading">Python 中的协同程序</h2>
<p class="Para" id="Par114">在计算机科学中，生成器是<em class="EmphasisTypeItalic ">协同程序</em>的一个特例，它可以挂起自己，并将执行传递给任何其他协同程序，当它们接收到返回值时继续执行。我们的<code>inlineCallbacks</code>修饰生成器类似于协程，因为它可以产生和接收值，但是它不像协程，它不能像调用任何其他函数那样直接调用另一个生成器。相反，它需要<code>inlineCallbacks</code>内部的机器来代表它将执行任务交给另一个生成器。这个机器管理执行代码的请求，并将结果返回给请求者，被称为<em class="EmphasisTypeItalic ">蹦床</em>。为了理解其中的原因，想象一下执行就好像在不同的发生器之间反弹<code>inlineCallbacks</code>。</p>
<h3 class="Heading">产自的协同程序</h3>
<p>Python 3.3 引入了一种新的语法，允许一个生成器直接将其执行委托给另一个生成器:<code>yield from</code>。以下 Python 3.3+专用代码演示了从另一个生成器生成的生成器的行为:</p>
<p><img alt="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig3_HTML.jpg" src="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig3_HTML.jpg" style="height:9.3em"/></p>
<p>图 2-3</p><p class="SimplePara">执行和数据流入流出<code>e</code>和<code>f</code>。执行向下移动，而数据流沿着实线箭头。</p>


<pre>&gt;&gt;&gt; def e():
...     a = yield 1
...     return a + 2
...
&gt;&gt;&gt; def f():
...     print("Begin f")
...     c = yield from e()
...     print(c)
...
&gt;&gt;&gt; g = f()
&gt;&gt;&gt; g.send(None)
Begin f
1
&gt;&gt;&gt;  g.send(2)
4
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p class="Para" id="Par116">生成器<code>e</code>的行为与上一节中描述的生成器函数完全一样:如果我们调用它，我们将通过调用它的<code>next</code>(或者传递它的<code>send</code>方法<code>None</code>)来启动返回的生成器，这将返回 1，它的<code>yield</code>的操作数；然后，我们可以用<code>send</code>将值传递回生成器，它会将操作数返回给下一个<code>yield</code>表达式或者返回给 return 语句(记住，在 Python 3 中，生成器可以返回值)。</p>
<p class="Para" id="Par117">由<code>f</code> <em class="EmphasisTypeItalic ">返回的生成器<code>g</code>从</em>产生由<code>e</code>返回的生成器，暂停以允许子生成器执行。对<code>g</code>发出的<code>next</code>、<code>send</code>和<code>throw</code>调用被代理到底层的<code>e</code>生成器，因此生成器<code>g</code>看起来是一个<code>e</code>生成器。在图<a href="#Fig3"> 2-3 </a>中，方框<strong class="EmphasisTypeBold "> A </strong>表示开始执行<code>g</code>的初始<code>g.send(None)</code>。执行通过<code>f()</code>的<code>yield from</code>移动到由<code>e()</code>返回的生成器，暂停在<code>e</code>主体内的<code>yield</code>表达式上，该表达式将<code>1</code>发送回<code>g.send(None)</code>。</p>
<p class="Para" id="Par118">当子生成器终止时，用<code>yield from</code>将执行委托给另一个生成器的生成器重新获得控制。图<a href="#Fig3"> 2-3 </a>中的框<strong class="EmphasisTypeBold "> B </strong>表示对<code>g.send(2)</code>的第二次调用，该调用通过暂停的<code>f</code>生成器将值<code>2</code>传递给子生成器<code>e</code>，子生成器恢复并将<code>2</code>赋给变量<code>a</code>。执行进行到<code>return</code>语句，并且<code>e</code>子生成器以值<code>4</code>退出。现在<code>f</code>在其<code>yield from</code>表达式的左侧重新开始，并将接收到的<code>4</code>赋给变量<code>c</code>。在<code>print</code>调用之后，没有进一步的<code>yield</code>或<code>yield from</code>表达式，因此<code>f()</code>终止，导致<code>g.send(2)</code>引发<code>StopIteration</code>错误。</p>
<p class="Para" id="Par119">这种语法不需要像<code>inlineCallbacks</code>这样的蹦床将调用从一个生成器分派到另一个生成器，因为它允许生成器直接将执行委托给其他生成器。有了<code>yield from</code>，Python 生成器的行为就像真正的协程一样。</p>

<h3 class="Heading">协同程序异步和等待</h3>
<p class="Para" id="Par120">不幸的是，<code>yield from</code>仍然遭受着和<code>yield</code>一样的不确定性:接受值和忽略值的生成器对于调用代码来说是一样的。Python 以后的版本通过在区分协程的<code>yield from</code>:<code>async</code>和<code>await</code>之上引入新的语法特性来解决这种歧义。</p>
<p>当应用于一个函数或方法定义时，<code>async</code>标记将那个函数或方法变成一个<em class="EmphasisTypeItalic ">协程</em>:</p>
<pre>&gt;&gt;&gt;  async def function(): pass
...
&gt;&gt;&gt; c = function()
&gt;&gt;&gt; c
&lt;coroutine object function at 0x9876543210&gt;

</pre>
<p>与生成器不同，协程不能迭代:</p>
<pre>&gt;&gt;&gt; list(function())
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
TypeError: 'coroutine' object is not iterable
&gt;&gt;&gt; next(function())
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
TypeError: 'coroutine' object is not iterable

</pre>
<p>像生成器一样，协程有<em class="EmphasisTypeItalic "> send </em>和<em class="EmphasisTypeItalic "> throw </em>方法，调用者可以用这些方法恢复它们:</p>
<pre>&gt;&gt;&gt; function().send(None)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration
&gt;&gt;&gt; function().throw(Exception)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 1, in function
Exception

</pre>
<p>协程可以<em class="EmphasisTypeItalic ">等待</em>其他协程，语义与从其他生成器生成的生成器相同:</p>
<pre>&gt;&gt;&gt; async def returnsValue(value):
...     return 1
...
&gt;&gt;&gt; async def awaitsCoroutine(c):
...     value = await c
...     print(value)
...
&gt;&gt;&gt; awaitsCoroutine(returnsValue(1)).send(None)
1
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p>这种行为展示了协同程序合成的先决条件，但是<code>await</code>做一些立即返回值的事情并不能激发它们在异步编程中的使用。我们需要能够向一个暂停的协程发送一个任意值，但是因为<code>async</code>和<code>await</code>的目的是呈现一个与普通生成器不兼容的 API，我们既不能像<code>yield from</code>那样<code>await</code>一个普通生成器，也不能像<code>yield</code>那样省略它的操作数:</p>
<pre>&gt;&gt;&gt; def plainGenerator():
...     yield 1
...
&gt;&gt;&gt; async def brokenCoroutineAwaitsGenerator():
...     await plainGenerator()
...
&gt;&gt;&gt; brokenCoroutineAwaitsGenerator().send(None)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 2, in brokenCoroutineAwaitsGenerator
TypeError: object generator can't be used in 'await' expression
&gt;&gt;&gt; async def brokenCoroutineAwaitsNothing():
...     await
  File "&lt;stdin&gt;", line 2
    await
        ^
SyntaxError: invalid syntax

</pre>
<p>为了学习如何用值恢复协程，我们回到<code>yield from</code>。我们之前的例子为<code>yield from</code>提供了另一个生成器，因此对包装生成器的<code>send</code>和<code>throw</code>方法的调用被代理到内部生成器。可能有许多生成器，每个生成器都通过<code>yield from</code>将执行委托给继任者，但是在底层，必须有一些东西产生向上的价值。例如，考虑一组五个发电机，如图<a href="#Fig4"> 2-4 </a>所示。</p>
<p><img alt="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig4_HTML.jpg" src="../images/455189_1_En_2_Chapter/455189_1_En_2_Fig4_HTML.jpg" style="height:9.08em"/></p>
<p>图 2-4</p><p class="SimplePara">一堆发电机。<code>g1</code>到<code>g4</code>已经向下委托<code>g5</code>执行。</p>


<pre>&gt;&gt;&gt; def g1(): yield from g2
...
&gt;&gt;&gt; def g2(): yield from g3
...
&gt;&gt;&gt; def g3(): yield from g4
...
&gt;&gt;&gt; def g4(): yield from g5
...
&gt;&gt;&gt; def g5(): yield 1

</pre>
<p><code>g1</code>、<code>g2</code>、<code>g3</code>和<code>g4</code>不能取得任何进展，直到<code>g5</code>产生一个将从<code>g4</code>传播到<code>g1</code>的值。<code>g5</code>不必是发电机，但是；如下例所示，<code>yield from</code>只需要一个<em class="EmphasisTypeItalic ">可迭代对象</em>来推进它的生成器:</p>
<pre>&gt;&gt;&gt; def yieldsToIterable(o):
...     print("Yielding from object of type", type(o))
...     yield from o
...
&gt;&gt;&gt; list(yieldsToIterable(range(3)))
Yielding from object of type &lt;class 'range'&gt;
[0, 1, 2]

</pre>
<p class="Para" id="Par128"><code>yieldsToIterable</code>将执行委托给它的参数，在本例中是一个<code>range</code>对象。通过构建一个列表来迭代<code>yieldsToIterable</code>生成器，演示了<code>range</code>对象就像生成器一样接管迭代。</p>
<p class="Para" id="Par129">用<code>async def</code>定义的协程与<code>yield from</code>共享它们的实现，因此通过适当的步骤，它们也可以<code>await</code>特殊类型的可迭代程序和生成器。</p>
<p>与前面的例子显示的相反，只要生成器<em class="EmphasisTypeItalic ">被用<code>types.coroutine</code>装饰器标记为协程，它们就可以被等待。使用这种修饰生成器的协程接收该生成器的返回值:</em></p>
<pre>&gt;&gt;&gt; import types
&gt;&gt;&gt; @types.coroutine
... def makeBase():
...     return (yield "hello from a base object")
...
&gt;&gt;&gt; async def awaitsBase(base):
...     value = await base
...     print("From awaitsBase:", value)
...
&gt;&gt;&gt; awaiter = awaitsBase(makeBase())
&gt;&gt;&gt; awaiter.send(None)
'hello from a base object'
&gt;&gt;&gt; awaiter.send("the result")
From awaits base: the result
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
StopIteration

</pre>
<p class="Para" id="Par131">用<code>send(None)</code>启动<code>awaitsBase</code>协程跳转到<code>base</code>生成器的<code>yield</code>语句，并遵循生成器的典型执行路径，返回<code>"hello from base object."</code>现在协程已将执行委托给<code>base</code>，因此<code>send("the result")</code>用该字符串恢复<code>base</code>。<code>base</code>立即<code>returns</code>这个值，这导致协程的<code>await</code>解析到它的值。</p>
<p class="Para" id="Par132">如果 Iterable 对象实现了一个返回迭代器的特殊的<code>__await__</code>方法，也可以等待它。这个迭代器的最终值——也就是说，无论它最后产生什么或者包装在一个<code>StopIteration</code>异常中——都将成为传递给<code>await</code>的结果。一个符合这个接口的物体被说成是<em class="EmphasisTypeItalic ">类未来</em>。当我们稍后探索<code>asyncio</code>时，我们将看到它的<code>Future</code>提供了这个接口，因此授予它它们的名字。</p>
<p>一个类似未来的对象的简单实现演示了控制流:</p>
<pre>class FutureLike(object):
    _MISSING="MISSING"
    def __init__(self):
        self.result = self._MISSING
    def __next__(self):
        if self.result is self._MISSING:
            return self
        raise StopIteration(self.result)
    def __iter__(self):
        return self
    def __await__(self):
        return iter(self)

async def awaitFutureLike(obj):
    result = await obj
    print(result)

obj = FutureLike()
coro = awaitFutureLike(obj)
assert coro.send(None) is obj
obj.result = "the result"
try:
    coro.send(None)
except StopIteration:
    pass

</pre>
<p class="Para" id="Par134"><code>FutureLike</code>的实例是可迭代的，因为它们的<code>__iter__</code>方法返回一个本身具有<code>__next__</code>方法的对象。在这种情况下，迭代一个<code>FutureLike</code>实例将一遍又一遍地产生同一个实例，直到它的<code>result</code>属性被设置，这时它将引发一个包含该值的<code>StopIteration</code>异常。这相当于来自发电机的<code>returning</code>值。</p>
<p class="Para" id="Par135"><code>FutureLike</code>的实例也是类似未来的，因为它们的<code>__await__</code>方法返回一个迭代器，所以<code>awaitFutureLike</code>可以<code>await</code>一个<code>FutureLike</code>的实例。通常，协程从<code>send(None)</code>开始。这将返回<code>awaitFutureLike</code>协程<code>await</code> s 的<code>FutureLike</code>实例，这是我们传递给它的同一个实例。设置<code>FutureLike</code>对象的<code>result</code>属性允许我们通过将其 await 解析为一个值来恢复协程，协程接收结果，打印结果，然后以一个<code>StopIteration</code>异常终止。</p>
<p class="Para" id="Par136">注意，第二个<code>coro.send</code>调用<em class="EmphasisTypeItalic ">也</em>将<code>None</code>传递给协程。协程，<code>await</code>类未来对象解析为这些对象的迭代器提供的最后一个值。它们仍然必须被恢复以利用这些值，但是它们必然会忽略它们的<code>send</code>方法的参数。</p>
<p class="Para" id="Par137">Twisted 提供了一个可适应的对象和一个协程适配器，这样协程和现有的 API 就可以无缝地交互。正如我们所见，协程与<code>asyncio</code>是完全分离的，所以我们在本节讨论的扭曲 API 不足以集成两者。我们将在下一章学习必要的附加 API。</p>


<h2 class="Heading">等待延期</h2>
<p>从 Twisted 16.4.0 开始，延迟是类似未来的对象，提供了一致的<code>__next__</code>、<code>__iter__</code>和<code>__await__</code>方法。这允许我们用一个<code>Deferred</code>替换前面代码中的<code>FutureLike</code>:</p>
<pre>from twisted.internet.defer import Deferred

async def awaitFutureLike(obj):
    result = await obj
    print(result)

obj = Deferred()
coro = awaitFutureLike(obj)
assert coro.send(None) is obj
obj.callback("the result")
try:
    coro.send(None)
except StopIteration:
    pass

</pre>
<p><code>awaiting</code>一个<code>Deferred</code>解析为<code>Deferred</code>在其正常回调和错误返回处理循环后做的任何事情:</p>
<pre>&gt;&gt;&gt; from twisted.internet.defer import Deferred
&gt;&gt;&gt; import operator
&gt;&gt;&gt; d = Deferred()
&gt;&gt;&gt; d.addCallback(print, "was received by a callback")
&lt;Deferred at 0x7eff85886160&gt;
&gt;&gt;&gt; d.addCallback(operator.add, 2)
&lt;Deferred at 0x7eff85886160&gt;
&gt;&gt;&gt; async def awaitDeferred():
...     await d
...
&gt;&gt;&gt; g = awaitDeferred()
&gt;&gt;&gt; g.send(None)
&lt;Deferred at 0x7eff85886160&gt;
&gt;&gt;&gt; d.callback(1)
1 was received by a callback
&gt;&gt;&gt; g.send(None)
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "&lt;stdin&gt;", line 2, in awaitDeferred
  File "twisted/src/twisted/internet/defer.py", line 746, in send
    raise result.value
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

</pre>
<p class="Para" id="Par140">我们的<code>Deferred</code>的<code>print</code>回调运行，但返回<code>None</code>，导致第二次回调失败，当它试图向第一个参数添加 2 时，返回<code>TypeError</code>。恢复的协程因此失败，并且<code>TypeError</code>存储在<code>Deferred</code>中。</p>
<p class="Para" id="Par141">在这种情况下，协程和<code>Deferreds</code>的组合暴露了一个 bug，但是测试的代码路径表明错误和数据在两者之间自然地流动。</p>
<p class="Para" id="Par142">允许我们在协程中调用扭曲的 API，但是如果我们想让扭曲的 API 使用我们的协程呢？</p>

<h2 class="Heading">使用 ensureDeferred 延迟的协同例程</h2>
<p class="Para" id="Par143">Twisted 可以用<code>Deferreds</code>包装协程，允许期望<code>Deferreds</code>的 API 接受协程。</p>
<p><code>twisted.internet.defer.</code> <code>ensureDeferred</code>接受一个协程对象并返回一个 Deferred，当协程返回一个:</p>
<pre>&gt;&gt;&gt; from twisted.internet.defer import Deferred, ensureDeferred
&gt;&gt;&gt; async def asyncIncrement(d):
...     x = await d
...     return x + 1
...
&gt;&gt;&gt; awaited = Deferred()
&gt;&gt;&gt; addDeferred = ensureDeferred(asyncIncrement(awaited))
&gt;&gt;&gt; addDeferred.addCallback(print)
&lt;Deferred at0x12345&gt;
&gt;&gt;&gt; awaited.callback(1)
2
&gt;&gt;&gt;

</pre>
<p>我们的协程<code>asyncIncrement awaits</code>是一个解析为一个数字的对象，然后返回这个数字和 1 的和。我们用<code>ensureDeferred</code>将它转换成一个<code>Deferred</code>，分配给<code>addDeferred</code>，然后给它添加一个<code>print</code>回调。回调<code>asyncIncrement</code>等待的<code>awaited Deferred</code>依次回调<code>ensureDeferred</code>返回的<code>addDeferred Deferred</code>，而不需要我们调用<code>send</code>。换句话说，<code>addDeferred</code>的行为与手动构建的<code>Deferred</code>相同。异常传播也以同样的方式工作:</p>
<pre>&gt;&gt;&gt;from twisted.internet.defer import Deferred, ensureDeferred
&gt;&gt;&gt; async def asyncAdd(d):
...     x = await d
...     return x + 1
...
&gt;&gt;&gt;awaited = Deferred()
&gt;&gt;&gt;addDeferred = ensureDeferred(asyncAdd(awaited))
&gt;&gt;&gt;addDeferred.addErrback(print)
Unhandled error in Deferred:

&lt;Deferred at0x7eff857f0470&gt;
&gt;&gt;&gt;awaited.callback(None)
[Failure  instance:  Traceback:&lt;  class 'TypeError'&gt;:  ...
...
&lt;stdin&gt;:3:asyncAdd
]

</pre>
<p class="Para" id="Par146">协同程序比<code>Deferred</code>管理的回调更类似于同步代码，Twisted 使得使用协同程序变得足够容易，以至于你可能会怀疑<code>Deferred</code>是否会带来麻烦。一个显而易见的答案是它们已经被使用过了；许多扭曲的代码使用了<code>Deferred</code>,所以即使你很少使用它们，你仍然需要熟悉它们。不使用协程的另一个原因是，您必须编写在 Python 2 上运行的代码。随着 Python 2 寿终正寝，这已经不再是一个问题，PyPy，一个替代的 Python 运行时，它的实时(JIT)编译器可以极大地提高纯 Python 代码的速度，扩展了它们对 Python 3 的支持。</p>
<p class="Para" id="Par147">然而，为什么 Twisted 的<code>Deferreds</code>在一个后协同程序的世界里仍然有价值，还有一些不太明显但更持久的原因。</p>

<h2 class="Heading">多路传输延迟</h2>
<p>如果我们想要两个异步操作的结果，其中一个可能在另一个之前完成，会发生什么？例如，假设我们编写一个程序，同时发出两个 HTTP 请求:</p>
<pre>def issueTwo(url1, url2):
    urlDeferreds = [retrieveURL(url1), retrieveURL(url2)]
    ...

</pre>
<p>协程会让我们依次等待每一个:</p>
<pre>async def issueTwo(url1, url2):
    urlDeferreds = [retrieveURL(url1),  retrieveURL(url2)]
    for d in urlDeferreds:
        result = await d
        doSomethingWith(result)

</pre>
<p class="Para" id="Par150">当<code>issueTwo await</code>完成其中一个的时候，反应堆将继续回收<code>url1</code>和<code>url2</code>；等待<code>url1</code>的回收完成并不妨碍反应堆回收<code>url2</code>。这种并发性确实是异步和事件驱动编程的要点！</p>
<p class="Para" id="Par151">然而，随着操作变得更加复杂，这种效率变得不那么重要了。假设我们只想要首先检索的 URL。我们不能只使用<code>await</code>来写一个<code>fastestOfTwo</code>协程，因为我们不知道先给哪个<code>await</code>。只有反应器知道指示协程值准备就绪的底层事件何时发生，并且如果我们只有协程，事件循环将不得不暴露同步原语，该原语同时等待多个协程并检查是否所有协程都已完成。</p>
<p class="Para" id="Par152">幸运的是，无需特殊的反应堆级同步机制，多个<code>Deferreds</code>就可以轻松复用成单个<code>Deferred</code>。最简单地说，<code>twisted.internet.defer.DeferredList</code>是一个<code>Deferred</code>，它接受一个延期列表，并在所有这些<code>Deferreds</code>都有值时回调自己。</p>
<p>考虑以下代码:</p>
<pre>&gt;&gt;&gt; from twisted.internet.defer import Deferred, DeferredList
&gt;&gt;&gt;  url1 = Deferred()
&gt;&gt;&gt;  url2 = Deferred()
&gt;&gt;&gt; urlList = DeferredList([url1, url2])
&gt;&gt;&gt; urlList.addCallback(print)
&lt;Deferred at 0x123456&gt;
&gt;&gt;&gt; url2.callback("url2")
&gt;&gt;&gt; url1.callback("url1")
[(True, "url1)", (True, "url2")]

</pre>
<p class="Para" id="Par154"><code>DeferredList</code> urlList 包装了两个<code>url1</code>和<code>url2 Deferreds</code>，并有一个<code>print</code>函数作为自己的回调函数。该回调仅在<code>url1</code>和<code>url2</code>都被回调后运行，因此<code>urlList</code>与上面的<code>issueTwo</code>协程中的全有或全无同步相匹配。</p>
<p class="Para" id="Par155">第一个线索是<code>DeferredList</code>更强大的特性集在于它返回给回调函数的<code>list</code>。每个元素是一个长度为 2 的<code>tuple</code>；第二个元素显然是传入的<code>list</code>中同一索引处的<code>Deferred</code>的值，所以索引 0 的第二个元组成员是<code>"url1"</code>，对应于索引 0 处的<code>url1 Deferred</code>。</p>
<p class="Para" id="Par156"><code>tuple</code>中的第一项表示<code>Deferred</code>是否成功终止。<code>url1</code>和<code>url2</code>都解析为字符串，而不是<code>Failures</code>，因此结果列表中相应的索引将<code>True</code>作为它们的第一个元素。</p>
<p>导致至少一个<code>DeferredList</code>的<code>Deferreds</code>失败演示了<code>Failures</code>是如何通信的:</p>
<pre>&gt;&gt;&gt; succeeds = Deferred()
&gt;&gt;&gt; fails = Deferred()
&gt;&gt;&gt; listOfDeferreds = DeferredList([succeeds, fails])
&gt;&gt;&gt; listOfDeferreds.addCallback(print)
&lt;Deferred at 0x1234567&gt;
&gt;&gt;&gt; fails.errback(Exception())
&gt;&gt;&gt; succeeds.callback("OK")
[(True, 'OK'), (False, &lt;twisted.python.failure.Failure builtins.Exception: &gt;)]

</pre>
<p class="Para" id="Par158">现在，返回列表中的第二个元组将<code>False</code>作为其第一个元素，并将代表导致其<code>Deferred</code>失败的<code>Exception</code>的<code>Failure</code>作为其第二个项目。</p>
<p class="Para" id="Par159">这个特殊的(<code>success</code>，<code>value or Failure</code>)对列表通过使用<code>Failures</code>的回溯捕获工具保留了所有可能的信息。作为这种方法带来的灵活性的一个例子，<code>DeferredList</code>的用户可以在一次回调中轻松地过滤聚合结果。</p>
<p class="Para" id="Par160">有了<code>DeferredList</code>的基本行为，我们可以研究允许我们实现<code>fastestOfTwo</code> : <code>fireOnOneCallback</code>的附加特性。</p>
<p>当<code>list</code>中的任何一个<code>Deferreds</code>有值时，<code>fireOnOneCallback</code>选项指示<code>DeferredList</code>回调自己:</p>
<pre>&gt;&gt;&gt; noValue = Deferred()
&gt;&gt;&gt; getsValue = Deferred()
&gt;&gt;&gt; waitsForOne = DeferredList([noValue, getsValue], fireOnOneCallback=True)
&gt;&gt;&gt; waitsForOne.addCallback(print)
&lt;Deferred at 0x12345678&gt;
&gt;&gt;&gt; getsValue.callback("the value") ('the  value',  1)

</pre>
<p class="Para" id="Par162">现在，当只有<code>getsValue Deferred</code>解析为一个值时，<code>waitsForOne</code>的<code>print</code>回调就会运行。传递给回调函数的值<code>DeferredList</code>也是一个长度为 2 的<code>tuple</code>，但是这一次，第一项是对应的<code>Deferred</code>解析到的值，而第二项是它在列表中的索引。<code>getsValue</code>用<code>"the value,"</code>回调，它是我们传递给<code>DeferredList</code>的列表中的第二个项目，所以回调接收<code>("the value," 1)</code>作为结果。</p>
<p>我们现在可以实现<code>fastestOfTwo</code>:</p>
<pre>def fastestOfTwo(url1, url2):
    def extractValue(valueAndIndex):
        value, index = valueAndIndex
        return value
    urlList = DeferredList([retrieveURL(url1), retrieveURL(url2)],
                          fireOnOneCallback=True,
                          fireOnOneErrback=True)
    return urlList.addCallback(extractValue)

</pre>
<p><code>DeferredList</code>也允许用<code>fireOnOneErrback</code>模拟多路传输错误。在第一个错误时触发<code>DeferredList</code>并展开它的值是一种常见的模式，Twisted 在<code>twisted.internet.defer.gatherResults</code>中提供了一个方便的包装器:</p>
<pre>&gt;&gt;&gt; from twisted.internet.defer import Deferred, gatherResults
&gt;&gt;&gt; d1, d2 = Deferred(), Deferred()
&gt;&gt;&gt; results = gatherResults([d1, d2])
&gt;&gt;&gt; results.addCallback(print)
&lt;Deferred at 0x123456789&gt;
&gt;&gt;&gt; d1.callback(1)
&gt;&gt;&gt; d2.callback(2)
&gt;&gt;&gt; [1, 2]
&gt;&gt;&gt; d1, d2 = Deferred(), Deferred()
&gt;&gt;&gt; fails = gatherResults([d1,  d2])
&gt;&gt;&gt; fails.addErrback(print)
&lt;Deferred at 0x1234567890&gt;
&gt;&gt;&gt; d1.errback(Exception())
[[Failure instance: Traceback ...: &lt;class 'Exception'&gt;: ]]

</pre>
<p class="Para" id="Par165">回想一下，<code>Failure</code>的<code>__str__</code>方法返回一个以<code>[]</code>开始和结束的字符串，因此打印出的失败出现了两组括号:一组来自其<code>__str__</code>，另一组来自其包含的<code>list</code>。</p>
<p class="Para" id="Par166">还要注意的是<code>gatherResults</code>等待<em class="EmphasisTypeItalic ">所有</em>成功<code>Deferreds</code>，所以它不能用于<code>fastestOfTwo</code></p>
<p class="Para" id="Par167"><code>DeferredList</code>和<code>gatherResults</code>提供了允许复杂行为但隐含分支的高级 APIs 每个选项的输出取决于它们自己的选项和它们包装的<code>Deferred</code>的输出之间的相互作用。任何一个方面的改变都可能导致意想不到的输出，从而产生令人不快的 bug。</p>
<p class="Para" id="Par168">这超出了<code>Deferred</code> s 的一般间接性:因为<code>Deferred.callback</code>几乎总是由反应器调用，而不是由间接操纵套接字的代码用户代码调用，所以在异常的来源和它的最终原因之间可能存在差距。</p>
<p class="Para" id="Par169">Twisted 通过提供对测试的特殊支持解决了异步代码固有的困难。</p>

<h2 class="Heading">测试延期</h2>
<p class="Para" id="Par170">在前一章中，我们看到 Twisted 的<code>trial.unittest</code>包提供了一个<code>SynchronousTestCase</code>，它的 API 模仿了<code>unittest.TestCase</code>的。事实上，<code>SynchronousTestCase</code>的 API 是<code>unittest.TestCase</code>的超集，它的附加特性的重要部分涉及到关于<code>Deferred</code>的断言</p>
<p>我们可以通过为上一节定义的<code>fastestOfTwo</code>函数编写测试来探索这些特性。首先，我们将把它一般化，接受任意两个<code>Deferreds</code>，而不是检索 URL 本身:</p>
<pre>def fastestOfTwo(d1, d2):
    def extractValue(valueAndIndex):
        value, index = valueAndIndex
        return value
    urlList = DeferredList([d1, d2],
                          fireOnOneCallback=True,
                          fireOnOneErrback=True)
    return urlList.addCallback(extractValue)

</pre>
<p>我们可以为这个新版本的<code>fastestOfTwo</code>编写的第一个测试断言，当它的两个<code>Deferreds</code>都没有解析为值时，它返回的<code>Deferred</code>没有解析为值:</p>
<pre>from twisted.internet import defer
from twisted.trial import unittest

class FastestOfTwoTests(unittest.SynchronousTestCase):
    def test_noResult(self):
        d1 = defer.Deferred()
        self.assertNoResult(d1)
        d2=defer.Deferred()
        self.assertNoResult(d2)
        self.assertNoResult(fastestOfTwo(d1, d2))

</pre>
<p class="Para" id="Par173">顾名思义，synchronoustestcase . assertnoresult 断言它所传递的延迟没有结果，这是一个很有价值的工具，可以确保执行符合您的预期。</p>
<p>然而，当它们确实有结果时，是最有用的。在<code>fastestOfTwo</code>的情况下，我们期望返回的<code>Deferred</code>取两个<code>Deferreds</code>中第一个的值:</p>
<pre>def test_resultIsFirstDeferredsResult(self):
    getsResultFirst = defer.Deferred()
    neverGetsResult = defer.Deferred()
    fastestDeferred = fastestOfTwo(getsResultFirst, neverGetsResult)
    self.assertNoResult(fastestDeferred)
    result = "the result"
    getsResultFirst.callback(result)
    actualResult = self.successResultOf(fastestDeferred)
    self.assertIs(result, actualResult)

</pre>
<p class="Para" id="Par175"><code>SynchronousTestCase.successResultOf</code>要么返回<code>Deferred</code>的当前结果，要么导致其测试失败。我们的测试在用它回调<code>getsResultFirst</code>之后，用它从<code>fastestDeferred</code>中提取<code>"the result"</code>，这样测试可以断言<code>fastestOfTwo</code>确实返回了第一个可用的结果。</p>
<p class="Para" id="Par176">注意，在我们回调<code>getsResultFirst</code>之前，我们仍然断言<code>fastestOfTwo</code>返回的<code>Deferred</code>没有结果。鉴于<code>test_noResult</code>已经做出了这个断言，这看起来可能是多余的，但是请记住，在您的代码添加回调或错误返回之前，可以回调<code>Deferred</code> s。在这种情况下，<code>fastestOfTwo</code>可能会错误地返回一个已经用<code>the result</code>回调的<code>Deferred</code>，而忽略传入的<code>Deferred</code> s，然而我们的测试仍然会通过。这在如此简单的代码中是不太可能的，但是当 a <code>Deferred</code>得到结果时，关于<em class="EmphasisTypeItalic ">的隐含假设可能会潜入代码中，导致测试忽略 bug。断言<code>Deferred</code>实际上处于给定的状态是一种好的做法，而不是假设这样以避免这些错误，并且更好的做法是针对已经有结果的<code>Deferred</code>和没有结果的<code>Deferred</code>来测试您的代码。</em></p>
<p>我们可以添加一个测试，断言即使在<code>Deferred</code>已经触发时<code>fastestOfTwo</code>也能工作:</p>
<pre>def test_firedDeferredIsFirstResult(self):
    result = "the result"
    fastestDeferred = fastestOfTwo(defer.Deferred(),
                                 defer.succeed(result))
    actualResult = self.successResultOf(fastestDeferred)
    self.assertIs(result, actualResult)

</pre>
<p class="Para" id="Par178"><code>twisted.internet.defer.succeed</code>函数接受一个参数并返回一个<code>Deferred</code>,这个参数会立即被回调，所以<code>fastestOfTwo</code>的第二个参数是一个<code>Deferred</code>,在任何<code>fastestOfTwo</code>运行之前，它已经被用<code>the result</code>回调了。</p>
<p>为了完整起见，我们还可以测试当<code>fastestOfTwo</code>收到两个已经被回调的<code>Deferreds</code>时会发生什么:</p>
<pre>def test_bothDeferredsFired(self):
    first = "first"
    second = "second"
    fastestDeferred = fastestOfTwo(defer.succeed(first),
                                 defer.succeed(second))
    actualResult = self.successResultOf(fastestDeferred)
    self.assertIs(first, actualResult)

</pre>
<p class="Para" id="Par180">底层的<code>DeferredList</code>将其内部处理回调按顺序添加到其列表中的每个<code>Deferreds</code>中。有了<code>fireOnOneCallback=True</code>，列表中最早有结果的<code>Deferred</code>回调代表列表的<code>Deferred</code>。在我们的测试中，我们期望<code>first</code>是回调<code>fastestDeferred</code>的值。</p>
<p>错误处理是测试的关键部分，所以我们对<code>fastestDeferred</code>的测试也应该测试它如何处理<code>Failure</code>。为了保持测试简短，我们将只展示在<code>Deferred</code>被传递到<code>fastestOfTwo</code>之前失败的情况:</p>
<pre>def test_failDeferred(self):
    class ExceptionType(Exception):
        pass
fastestDeferred = fastestOfTwo(defer.fail(ExceptionType()),
                             defer.Deferred())
failure = self.failureResultOf(fastestDeferred)
failure.trap(defer.FirstError)
failure.value.subFailure.trap(ExceptionType)

</pre>
<p class="Para" id="Par182">像<code>SynchronousTestCase.successResultOf</code>，<code>SynchronousTestCase.failureResultOf</code>从一个<code>Deferred</code>返回当前的<code>Failure</code>；如果<code>Deferred</code>还没有被调用或者没有<code>-Failure</code>结果，<code>failureResultOf</code>导致测试失败。</p>
<p class="Para" id="Par183">因为返回的对象是一个<code>Failure</code>，所以我们可以在 errbacks 中使用的所有方法和属性在我们的测试中都是可用的。<code>DeferredList</code>用<code>fireOnOneErrback=True</code>将失败包装在<code>twisted.internet.defer.FirstError</code>异常中，所以我们在测试中使用了<code>trap</code>这种类型；如果<code>Failure</code>包装了任何其他异常，<code>trap</code>将再次引发它。导致<code>FirstError</code>的底层<code>Failure</code>在其<code>subFailure</code>属性上是可访问的，并且由于我们传入了<code>ExceptionType</code>的一个实例，我们<code>trap</code>断言第一个<code>Deferred</code>由于预期的原因而失败。</p>
<p class="Para" id="Par184">使用<code>successResultOf</code>和<code>failureResultOf</code>的<code>assertNoResult</code>鼓励使用关于<code>Deferred</code>状态的显式假设来编写测试。正如<code>fastestOfTwo</code>所展示的，即使是对<code>Deferred</code>的简单使用也必须进行隐式排序依赖和错误处理测试。这些也是协程和任何其他并发原语的关注点。Twisted 的测试套件自然拥有在<code>Deferred</code>环境中处理常见并发问题的最佳工具。</p>

<h2 class="Heading">摘要</h2>
<p class="Para" id="Par185">这一章通过解释事件处理程序是一种<code>_callback_</code>的方式，继承了上一章未完成的事件驱动编程。由于<em class="EmphasisTypeItalic ">延续传递式</em>的理论力量，非常复杂的程序可以用回调来表达。回调通过直接调用其他回调来传递值，而不是返回给它们的调用者。我们将这种组合命名为<em class="EmphasisTypeItalic ">内部组合</em>,因为它发生在每个回调的主体中。</p>
<p class="Para" id="Par186">内部组合使得维护回调驱动的程序变得困难:每个回调都必须知道它的后继者的名字和签名，这样它才能调用它。对一系列回调进行重新排序或消除一个回调可能需要修改几个回调。一个解决方案在于<em class="EmphasisTypeItalic ">异步编程</em>的范例，它允许程序在所有输入准备好之前继续运行。代表异步结果的<em class="EmphasisTypeItalic ">占位符值</em>可以收集回调，然后在真实值可用时运行它们。这个占位符允许回调返回值，从而在外部组合<em class="EmphasisTypeItalic "/>，反过来使得逻辑单元不知道它们是如何以及在哪里被使用的。使用这些异步占位符的事件驱动代码可以像非回调驱动代码一样被分解。</p>
<p class="Para" id="Par187">Twisted 的异步占位符值是<code>Deferred</code>。我们看到<code>Deferred</code>在一个循环中运行它们的回调，将一个的结果传递给下一个，并在任何异常时调用错误处理程序或错误返回。T2 内部的这个处理循环使它们成为强大的控制流抽象 T4。</p>
<p class="Para" id="Par188">控制流抽象的一个重要部分是以不同的方式响应不同的错误。Twisted 的<code>Failure</code>类捕获回溯信息以及引发的异常，并公开允许 errbacks 过滤和重新引发异常的实用方法。我们看到了回调和错误返回如何完全代表使用<code>try</code>和<code>except</code>的同步代码。</p>
<p class="Para" id="Par189">就像回调允许组合一样，它们自己组合。当回调或错误返回一个<code>Deferred</code>时，该回调或错误自身的<code>Deferred</code>暂停其执行，直到新的<code>Deferred</code>完成。这意味着返回<code>Deferred</code>的函数和方法可以被用作回调和错误返回，而不需要开发人员做任何特别的努力。</p>
<p class="Para" id="Par190">尽管<code>Deferred</code>功能强大，但它们并不是组成异步动作的唯一方式。Python 的<em class="EmphasisTypeItalic ">生成器</em>可以暂停它们的执行，并在从外部来源接收到值后继续执行。这个控制流映射到由延迟器提供的控制流，回调和错误可以通过使用<code>inlineCallbacks</code>转移到生成器中。</p>
<p class="Para" id="Par191">然而，生成器是不明确的，因为它们可能表示简单的迭代器或类似于<code>Deferred</code>的控制流。Python 3.5 增加了对<em class="EmphasisTypeItalic ">协程</em>的特殊支持，这些协程是以控制流为中心的生成器，可以通过将执行委托给其他协程来挂起自己，而不需要<code>inlineCallbacks</code>。协程可以<code>await</code>直接扭曲<code>Deferred</code>的，可以用<code>ensureDeferred</code>变成<code>Deferred</code>的。这些 API 允许 Twisted 无缝地使用协程。</p>
<p class="Para" id="Par192">不是所有的程序都可以用协程直接表达:我们的<code>fastestOfTwo</code>例子需要同时等待两件事情。幸运的是，<code>DeferredList</code>，一个建立在<code>Deferreds</code>之上的抽象，允许 Twisted 去复用的异步结果。</p>
<p class="Para" id="Par193">Twisted 还特别支持测试<code>Deferred</code>s。<code>SynchronousTestCase</code>提供了<code>assertNoResult</code>、<code>successResultOf</code>和<code>failureResultOf</code>，允许测试对<code>Deferred</code> s 的状态做出精确的断言。影响所有原语(协程、生成器和<code>Deferred</code> s)的并发问题可以用这套工具进行测试。</p>


</body>
</html>