# 十九、异常

当你的程序出错时，你想让用户看不到红色的 Python 错误信息吗？您想让您的程序不挂起吗？如果是这样，那么你需要异常。

异常用于处理代码执行过程中可能出现的异常情况。异常通常用于文件和网络操作。这使得代码能够优雅地处理磁盘空间不足、网络错误或权限错误。

## 词汇

处理异常时会用到几个术语和短语。以下是最常见的:

*   异常:这个术语可能有两种意思。首先，导致异常程序流的条件。或者它可以用于引用表示数据条件的对象。每个异常都有一个保存相关信息的对象。
*   异常处理:处理正常程序流程异常的过程。
*   Catch 块或异常块:处理异常情况的代码被称为捕获异常。
*   抛出或抛出:当检测到程序流的异常情况时，创建一个异常对象的实例。然后将它抛出或引发给将捕获它的代码。
*   未处理的异常或未捕获的异常:抛出但从未捕获的异常。这通常会导致错误和程序结束或崩溃。
*   Try 块:一组可能抛出异常的代码。

大多数编程语言都使用抛出和捕捉这两个术语。不幸的是 Python 没有。Python 使用 raise 和 exception。我们在这里介绍抛出/捕捉词汇，因为它们是行业中最流行的术语。

## 异常处理

处理异常的代码很简单。请参见下面的示例:

`# Divide by zero`

`try:`

`x = 5 / 0`

`except:`

`print("Error dividing by zero")`

第 2 行是`try`语句。它下面的每一行都是 try 块的一部分。在`try`块下面可能没有不以`except`语句开始的未缩进代码。`try`语句定义了代码试图执行的一段代码。

如果在代码处理过程中出现任何异常，执行将立即跳转到 catch 块。该代码块缩进在第 4 行的`except`语句下。这段代码负责处理错误。

程序可以使用异常来捕捉从文本到数字转换过程中出现的错误。例如:

`# Invalid number conversion`

`try:`

`x = int("fred")`

`except:`

`print("Error converting fred to a number")`

第 3 行将抛出一个异常，因为`"fred"`不能被转换成整数。第 5 行的代码将打印出一条错误消息。

下面是这个例子的扩展版本。它对用户的输入进行错误检查，以确保输入的是整数。如果用户不输入整数，程序会一直要求输入。代码使用异常处理来捕获可能发生在第 5 行的转换错误。如果用户输入的不是整数，当在第 5 行转换为数字时会抛出异常。如果第 5 行出现异常，第 6 行将`number_entered`设置为`True`的代码将不会运行。

`number_entered = False`

`while not number_entered:`

`number_string = input("Enter an integer: ")`

`try:`

`n = int(number_string)`

`number_entered = True`

`except:`

`print("Error, invalid integer")`

文件在操作过程中特别容易出错。磁盘可能会被填满，用户可能会删除正在写入的文件，文件可能会被移动，或者 USB 驱动器可能会在操作过程中被拔出。使用异常处理也可以很容易地捕获这些类型的错误。

`# Error opening file`

`try:`

`my_file = open("myfile.txt")`

`except:`

`print("Error opening file")`

可以捕获多种类型的错误，并以不同的方式进行处理。向用户提供比简单的“发生了错误”更准确的错误信息会很有用

在下面的代码中，不同类型的错误可能发生在`try`块中。通过将`IOError`放在`except`之后，该代码将只处理关于输入和输出(IO)的错误。同样，由于`ValueError`，下一个`except`模块仅处理转换值的误差，下一个模块覆盖除以零的误差。最后的异常处理发生在最后两行。由于该`except`块不包括特定类型的错误，所以它将处理上述先前的`except`块未涵盖的任何错误。总括`except`必须总是最后。

`# Multiple errors`

`try:`

`my_file = open("myfile.txt")`

`my_line = my_file.readline()`

`my_int = int(s.strip())`

`my_calculated_value = 101 / my_int`

`except IOError:`

`print("I/O error")`

`except ValueError:`

`print("Could not convert data to an integer.")`

`except ZeroDivisionError:`

`print("Division by zero error")`

`except:`

`print("Unexpected error")`

可从以下网址获得内置异常列表: [`http://docs.python.org/library/exceptions.html`](http://docs.python.org/library/exceptions.html)

## 示例:保存高分

这显示了如何在游戏之间保存高分。分数存储在一个名为`high_score.txt`的文件中。

`"""`

`Show how to use exceptions to save a high score for a game.`

`Sample Python/Pygame Programs`

[T2`http://programarcadegames.com/`](http://programarcadegames.com/)

`"""`

`def get_high_score():`

`# Default high score`

`high_score = 0`

`# Try to read the high score from a file`

`try:`

`high_score_file = open("high_score.txt", "r")`

`high_score = int(high_score_file.read())`

`high_score_file.close()`

`print("The high score is", high_score)`

`except IOError:`

`# Error reading file, no high score`

`print("There is no high score yet.")`

`except ValueError:`

`# There’s a file there, but we don’t understand the number.`

`print("I’m confused. Starting with no high score.")`

`return high_score`

`def save_high_score(new_high_score):`

`try:`

`# Write the file to disk`

`high_score_file = open("high_score.txt", "w")`

`high_score_file.write(str(new_high_score))`

`high_score_file.close()`

`except IOError:`

`# Hm, can’t write it.`

`print("Unable to save the high score.")`

`def main():`

`""" Main program is here. """`

`# Get the high score`

`high_score = get_high_score()`

`# Get the score from the current game`

`current_score = 0`

`try:`

`# Ask the user for his/her score`

`current_score = int(input("What is your score? "))`

`except ValueError:`

`# Error, can’t turn what they typed into a number`

`print("I don’t understand what you typed.")`

`# See if we have a new high score`

`if current_score > high_score:`

`# We do! Save to disk`

`print("Yea! New high score!")`

`save_high_score(current_score)`

`else:`

`print("Better luck next time.")`

`# Call the main function, start up the game`

`if __name__ == "__main__":`

`main()`

## 异常对象

关于错误的更多信息可以从异常对象中提取。在使用`as`关键字捕获错误时，可以检索这个对象。例如:

`try:`

`x = 5 / 0`

`except ZeroDivisionError as e:`

`print(e)`

`e`变量指向可以打印出来的关于异常的更多信息。使用异常对象可以做更多的事情，但不幸的是这超出了本章的范围。有关异常对象的详细信息，请查看 Python 在线文档。

## 异常生成

使用`raise`命令可能会产生异常。例如:

`# Generating exceptions`

`def get_input():`

`user_input = input("Enter something: ")`

`if len(user_input) == 0:`

`raise IOError("User entered nothing")`

`getInput()`

尝试使用上面的代码，并为引发的`IOError`添加异常处理。

也可以创建自定义异常，但这也超出了本书的范围。好奇的读者可以访问以下网站了解更多信息:

[T2`http://docs.python.org/tutorial/errors.html#raising-exceptions`](http://docs.python.org/tutorial/errors.html#raising-exceptions)

## 正确的异常使用

当`if`语句可以轻松处理条件时，不应该使用异常。正常代码在运行快乐路径场景时不应该引发异常。构造良好的 try/catch 代码很容易理解，但是涉及许多异常和跳转到不同处理程序的代码可能是调试的噩梦。(有一次，我被分配去调试读取 XML 文档的代码。它为所读取的文件的每一行生成了许多异常。它慢得令人难以置信，而且容易出错。该代码在读取文件的正常过程中应该从未生成过任何异常)。

## 回顾

### 多项选择测验

What is an exception? Something that results in abnormal program flow.   An `if` statement that is `False`.   Code that handles an unexpected condition in the program.   Paramore thinks you are the only one.     What is a `catch` or `exception` block? Something computers play in the back yard.   Code that may cause an error that needs to be handled.   Code that handles an unexpected condition in the program.   A block with 22 lines in it.     What is a `try` block? Something that results in abnormal program flow.   An `if` statement that is `False`.   Code that handles an unexpected condition in the program.   There is no `try` block, only `do` or `not do` blocks.   Code that may cause an error that needs to be handled.     What will print for `x`? `try:`         `x = 5/0`         `y = 10` `except:`         `print("Error")` `print(x)` 5/0   Infinity   5   0 because the error has been caught.   `x` will not print, there is an error.     What does the keyword `raise` do? Checks for errors.   Brings code back to life after it has been executed.   Generates a new exception that will be handled by a `try` block.   Generates a new exception that will be handled by an `except` block.     What will print for `y`? `try:`         `x = 5/0`         `y = 10` `except:`         `print("Error")` `print(y)` 10   Infinity   5   10 because the error has been caught.   `y` will not print, there is an error.     What is `e`? `try:`         `x = 5 / 0` `except ZeroDivisionError as e:`         `print(e)` 5   0   An object that stores data about the error.   A class that stores data about the error.   A library for exception handling.    

### 简答工作表

Define the following terms in your own words. Don’t just copy/paste from the book:

*   异常
*   异常处理
*   尝试阻止
*   捕捉块
*   未处理异常情况
*   扔

  Show how to modify the following code so that an error is printed if the number conversion is not successful. Modify this code; don’t just copy the example from the text. No need to ask again if the conversion is unsuccessful. `user_input_string = input("Enter a number:")` `user_value = int(user_input_string)`   What will the following code output? Predict, and then run the code to see if you are correct. Write your prediction here and if you are right. If you aren’t, make sure you understand why. (Make sure to write both the prediction, and the actual results. If the program raises an error, list that fact for this and the next problem as well.) `x = 5` `y = 0` `print("A")` `try:`     `print("B")`     `a = x / y`     `print("C")` `except:`     `print("D")` `print("E")` `print(a)`   What will the following code output? Predict, and then run the code to see if you are correct. Write your prediction here and if you are right. If you aren’t, make sure you understand why. `x = 5` `y = 10` `print("A")` `try:`     `print("B")`     `a = x / y`     `print("C")` `except:`     `print("D")` `print("E")` `print(a)`